os: Windows Server 2012

services:
  - iis

platform: Any CPU

configuration: Release

before_build: nuget restore FileTaggerMVC\FileTaggerMVC.sln

build:
    project: FileTaggerMVC\FileTaggerMVC.sln
    verbosity: minimal

environment:
    COVERALLS_REPO_TOKEN:  
       secure: F5Q88lzJGLHU+KOwsCn0BDu3pgwvxHgV2nfhaRmzscH9KQvc+NCcpUxP7ykSvEam
       
test:
  categories:
    only:
      - WaitForNUnit3Support